### ISSUE TITLE
Test coverage for labelled rewrites

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#904]
We should have unit tests to cover all the exotic behaviour that we encountered while implementing labelled rewrites:

- [x] #902 endomorphism on the circle, contracted at both ends (shouldn't be able to absorb a homotopy into the endomorphism) (test `hourglass_no_absorb`)
- [X] #899 contract endomorphism on the fully algebraic ring composed with weak unit (source and target cocone indices need to be calculated correctly) ((test `contract_with_weak_id(endomorphism_on_algebraic_ring)`)
- [X] #899 contract endomorphism on the half-algebraic half-homotopy ring composed with weak unit (collapse needs to consider multi-edges when searching for triangles) (test `contract_with_weak_id(endomorphism_on_half_algebraic_ring)`)
- [x] #898 contract 2D homotopy cap/cup composed with weak unit (source and target cocone indices need to be calculated correctly) (test `bead_through_cap_cup`, `contract_with_weak_id`)
- [X] #879 contract counit on endomorphism, composed with weak unit (test `contract_with_weak_id`)
- [x] #876 contract counit on a scalar, composed with weak unit (test `contract_with_weak_id`)
- [x] #875 contract endomorphism on a weak unit, composed with a weak unit (test `contract_with_weak_id(endomorphism_on_weak_unit)`
- [x] #856 braiding 3D scalar with a wire (test `three_dimensional_scalar_across_wire_preserves_label_neighbourhood`)
- [x] #840 #759 passing a unit through a braid (test `pull_through_braid`)
- [x] #828 unit (also bead on a wire) should not be bendable through cup (test `no_bend_cup`)
- [x] #823 should be able to create double-braids in all configurations (test `double_braid`)
- [x] #821 should be able to braid wire with cup/cap (test `cap_braid`)
- [x] #734 dually, should be able to pop wire off cap (test `cap_braid`)
- [x] #820 Reidemeister 1 should not contract, nor crash (test `no_reidemeister_1`)
- [x] #801 contracting homotopy circle (test `bubble_pop_2d`)
- [x] #798 endomorphism on a braid, composed with weak unit (test `contract_with_weak_id`)
- [x] #744 (expansion) interchanging a half-braid with a bead on a wire (test `bead_with_half_braid`)
- [x] #736 braiding a counit with a wire (3D) (test `counit_braid`)
- [x] #723 #597 make braid on same singular height as bead (test `braid_next_to_endomorphism`)
- [x] #722 should be able to contract two caps together (test `contract_two_caps`)
- [x] #720 expanded braid made by interchanging two beads on two wires should contract (test `bead_interchanger`)
- [x] #713 should be able to construct this generator (test `monoid_with_unit_to_id`)
- [x] #686 tricky cone-wise smoothing indices (test `monoid_tensor_bead_and_inverse`)
- [x] #681 should be able to contract 3D scalar with its inverse (test `scalar`)
- [x] #620 (factorization) bubbling should not stretch generators, and another test for a double braid (test `bead_no_stretch`)
- [x] #598 unbraiding a braid shouldn't introduce weak unit (test `braid_smooth`)
- [x] #568 test cone-wise smoothing, annihilation next to a bead (test `bead_tensor_bead_and_inverse`)

**Comment by calintat** [comment]
@NickHu can we close this?

**Comment by NickHu** [comment]
Yeah pretty much. I'll just add that we probably also want a test for #906, once we figure out what's going wrong there.

Also, for reference, `cargo nextest run` is like `cargo test` but it parallelises runs and is a lot faster.

**Comment by calintat** [comment]
Can we change the pre-commit hook and CI to use cargo-nexttest instead of cargo-test?

**Comment by NickHu** [comment]
In principle yes, but it's not immediately supported by the tool we use to generate the commit hook, so it's not entirely trivial. I've been meaning to move the commit hooks over to nix anyway, so I'll find time to do it then anyway.
