### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#93]
Following up from our stand-up this morning, I'm opening this issue for us to discuss potential global settings that should be added to the settings draw. So far we've spoken about:

- [x] Toggling wireframe rendering (blocked on #91)
- [x] Toggling smoothing (blocked on #91)
- [ ] Re-mapping keyboard shortcuts

Things we haven't spoken about but are probably worth having:

- [ ] Depth bounds for expensive search algorithms (connected to #84)

**Comment by jamievicary** [comment]
Sounds excellent Nathan, and thanks for picking up that nice possible
connection to #84.

**Comment by NickHu** [comment]
Layout also has a depth bound (hard-coded), not sure if we want to make this configurable

**Comment by jamievicary** [comment]
Layout should be superceded by the new cubicalisation algorithm.

**Comment by NickHu** [comment]
Even then, won't this have a depth bound if it's non-terminating?

**Comment by jamievicary** [comment]
It will be terminating!
